### ISSUE TITLE
If you modify the edge of the chuck the side chunk that will be generated will not connect

### ISSUE THREAD

**Issue by BlackStarMachine** [Eldemarkki/Marching-Cubes-Terrain#37] opened 2020-06-28 16:40 UTC
If you modify the border of chunk by either lowering or raising the terrain the side chunk that will be generated as you get closer will not connect with the modified one

**Comment by Eldemarkki** [comment] 2020-06-28 16:42
I've seen this happen before and fixed it, so it should not be happening anymore. But apparently, it is. Which branch did you encounter this on?

**Comment by Eldemarkki** [comment] 2020-06-28 17:14
Unable to reproduce in develop

**Comment by BlackStarMachine** [comment] 2020-06-28 20:22
Hey, I have encounter this issue in master branch. Is develop the latest version?

**Comment by Eldemarkki** [comment] 2020-06-28 20:32
Ok, thanks! Yes, develop is the latest version, however, develop may also be slightly unstable at times. 

I'll be merging develop into master soon (most likely this or next week, but I won't promise anything). 

There will be major changes to the whole project, so prepare for that. If you have already started developing on the master branch's API, I recommend starting to adjust it to the develop's API, so you'll be ready when it's merged. The new API will break some things, but it is a lot more modular and easier to extend upon.

**Comment by Eldemarkki** [comment] 2020-07-02 18:33
Fix released in master

**Closed by Eldemarkki** 2020-07-02 18:33 UTC
Labels: bug, fixed in next release, not reproducible
